### ISSUE TITLE
Access method registered as pg_tde_basic instead of pg_tde.

### ISSUE THREAD

**Issue by jeffreydwalter** [Percona-Lab/pg_tde#244]
RE: https://github.com/Percona-Lab/pg_tde/issues/43

The documentation indicates that the access method is called `pg_tde`, but the docker container creates it as `pg_tde_basic`.
```
pg_tde_test=# \dx
                 List of installed extensions
  Name   | Version |   Schema   |         Description          
---------+---------+------------+------------------------------
 pg_tde  | 1.0     | public     | pg_tde access method
 plpgsql | 1.0     | pg_catalog | PL/pgSQL procedural language
(2 rows)

pg_tde_test=# CREATE TABLE tde_test (id integer) USING pg_tde;
ERROR:  access method "pg_tde" does not exist
pg_tde_test=# SELECT * FROM pg_am;
  oid  |    amname    |       amhandler        | amtype 
-------+--------------+------------------------+--------
     2 | heap         | heap_tableam_handler   | t
   403 | btree        | bthandler              | i
   405 | hash         | hashhandler            | i
   783 | gist         | gisthandler            | i
  2742 | gin          | ginhandler             | i
  4000 | spgist       | spghandler             | i
  3580 | brin         | brinhandler            | i
 16412 | pg_tde_basic | pg_tdeam_basic_handler | t
(8 rows)

pg_tde_test=# CREATE TABLE tde_test (id integer) USING pg_tde_basic;
ERROR:  failed to retrieve principal key
pg_tde_test=# CREATE TABLE tde_test (id integer) USING pg_tde;
ERROR:  access method "pg_tde" does not exist
pg_tde_test=# CREATE EXTENSION pg_tde;
ERROR:  extension "pg_tde" already exists
```

**Comment by ImTheKai** [comment]
Hey,

Let me add some clarity here, as this is not fully documented yet.

This repo contains the extension code. The extension has two access methods: pg_tde_basic and pg_tde. The basic one only encrypts the tables and requires no core changes, so it is fully compatible with vanilla PostgreSQL.

The second access method, pg_tde (also part of this extension), is still developing. It aims to encrypt indexes and tables and requires a few additional hooks in PostgreSQL. For this, we're using the "Extensible storage manager API" patchset proposed by the Neon team in the community: [https://www.postgresql.org/message-id/flat/CYCZRFZES0OM.28GN7G5EDHOCN%40neon.tech#c602d28141f9f533005ec2596998ebaa](https://www.postgresql.org/message-id/flat/CYCZRFZES0OM.28GN7G5EDHOCN%40neon.tech#c602d28141f9f533005ec2596998ebaa).

We want to push these proposed changes so that the "full" version of our extension also becomes compatible with vanilla PostgreSQL. You can find these changes in the PostgreSQL fork we maintain at Percona-Lab: [https://github.com/Percona-Lab/postgres](https://github.com/Percona-Lab/postgres).

Please let me know if this makes things clearer to you @jeffreydwalter

**Comment by jeffreydwalter** [comment]
That does! Thank you!

**Comment by jeffreydwalter** [comment]
Would be nice to update the website documentation and readme to make that clear.

**Comment by ImTheKai** [comment]
Hey, for now I've changed the documentation to highlight the access method pg_tde_basic as the default - https://github.com/Percona-Lab/pg_tde/pull/245 

I'll work on another draft as an early stage information on what's behind the two different methods and why they do exist

**Comment by jeffreydwalter** [comment]
Sounds great! Thank you!
